### ISSUE TITLE
BioSample

### ISSUE THREAD

**Issue by themiszamani** [FC4E-WP5/pidmr-handle-proxy-lib#3]
Please add BioSample as provider 

https://pidmr.devel.argo.grnet.gr/managed-pids/view/38
https://www.ncbi.nlm.nih.gov/biosample/%s
^SAM[NED](\w)?\d+$
SAMEA2397676

**Comment by asajedi** [comment]
Done. Please check and close.

**Comment by themiszamani** [comment]
it is ok !!
